# [theme]
# primaryColor="#adb6c4"
# backgroundColor="#001b2e"
# secondaryBackgroundColor="#294c60"
# textColor="#ffefd3"

[theme]
primaryColor="#9ca3af"
backgroundColor="#000000"
secondaryBackgroundColor="#059669"
textColor="#f2f2f2"

[runner]
magicEnabled = false